select * from customer_shopping limit 10;
use data_analyse;


-- Q1. What is the total revenue generated by male vs. female customers?
select gender,sum(purchase_amount) as Total_Revenue from customer_shopping group by(gender) ;

-- --Q2. Which customers used a discount but still spent more than the average purchase amount?
select customer_id from customer_shopping where discount_applied="Yes" and purchase_amount>(select avg(purchase_amount) from customer_shopping);

-- --Q3. Which are the top 5 products with the highest average review rating?
select item_purchased,round(avg(review_rating),2) as average_rating from customer_shopping group by item_purchased order by average_rating desc limit 5 ;

-- --Q4. Compare the average Purchase Amounts between Standard and Express Shipping.
select shipping_type,round(avg(purchase_amount),2) from customer_shopping where shipping_type in ("Express","Standard") group by shipping_type;

-- --Q5. Do subscribed customers spend more? Compare average spend and total revenue between subscribers and non-subscribers.
select subscription_status,count(customer_id),sum(purchase_amount),avg(purchase_amount) from customer_shopping group by subscription_status ;

-- --Q6. Which 5 products have the highest percentage of purchases with discounts applied?
select item_purchased, sum(case when discount_applied="Yes" then 1 else 0 end)/count(item_purchased)*100 as percentage from customer_shopping group by item_purchased order by percentage desc limit 5 ;

-- --Q7. Segment customers into New, Returning, and Loyal based on their total number of previous purchases, and show the count of each segment.
with customer_type as(
select case when previous_purchases = 1 then "New" when previous_purchases between 2 and 10 then "Returning" else "Loyal" end as Customers from customer_shopping
)
select Customers ,count(*) from customer_type group by Customers;

-- or  

select case when previous_purchases = 1 then "New" when previous_purchases between 2 and 10 then "Returning" else "Loyal" end as Customers ,count(*) from customer_shopping group by Customers;


-- --Q8. What are the top 3 most purchased products within each category?
select * from (
select category,item_purchased,count(customer_id)as total_orders, row_number() over(partition by category order by count(customer_id) desc )as ranks from customer_shopping group by category,item_purchased
) t where ranks <4;

-- --Q9. Are customers who are repeat buyers (more than 5 previous purchases) also likely to subscribe?
select subscription_status,count(previous_purchases) from customer_shopping group by subscription_status having count(previous_purchases)>5 ;

-- --Q10. What is the revenue contribution of each age group?
select age_group,sum(purchase_amount) as revenue from customer_shopping group by age_group order by revenue desc;

-- or

SELECT 
    age_group,
    SUM(purchase_amount) AS revenue,
    round(SUM(purchase_amount) * 100.0 / SUM(SUM(purchase_amount)) over(),2) AS revenue_percentage
FROM customer_shopping
GROUP BY age_group 
ORDER BY revenue DESC;
